/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlumniIndexRouteImport } from './routes/alumni.index'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardChildRouteImport } from './routes/dashboard.child'
import { Route as DashboardGroupRouteImport } from './routes/dashboard.group'
import { Route as DashboardParentRouteImport } from './routes/dashboard.parent'
import { Route as DashboardSchoolRouteImport } from './routes/dashboard.school'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniIndexRoute = AlumniIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlumniRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChildRoute = DashboardChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupRoute = DashboardGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParentRoute = DashboardParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchoolRoute = DashboardSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/child': typeof DashboardChildRoute
  '/dashboard/group': typeof DashboardGroupRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/school': typeof DashboardSchoolRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/alumni/': typeof AlumniIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/child': typeof DashboardChildRoute
  '/dashboard/group': typeof DashboardGroupRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/school': typeof DashboardSchoolRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/alumni': typeof AlumniIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/child': typeof DashboardChildRoute
  '/dashboard/group': typeof DashboardGroupRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/school': typeof DashboardSchoolRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/alumni/': typeof AlumniIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumni'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/child'
    | '/dashboard/group'
    | '/dashboard/parent'
    | '/dashboard/school'
    | '/dashboard/teacher'
    | '/alumni/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/child'
    | '/dashboard/group'
    | '/dashboard/parent'
    | '/dashboard/school'
    | '/dashboard/teacher'
    | '/alumni'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/alumni'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/child'
    | '/dashboard/group'
    | '/dashboard/parent'
    | '/dashboard/school'
    | '/dashboard/teacher'
    | '/alumni/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumniRoute: typeof AlumniRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni/': {
      id: '/alumni/'
      path: '/'
      fullPath: '/alumni/'
      preLoaderRoute: typeof AlumniIndexRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/child': {
      id: '/dashboard/child'
      path: '/child'
      fullPath: '/dashboard/child'
      preLoaderRoute: typeof DashboardChildRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/group': {
      id: '/dashboard/group'
      path: '/group'
      fullPath: '/dashboard/group'
      preLoaderRoute: typeof DashboardGroupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parent': {
      id: '/dashboard/parent'
      path: '/parent'
      fullPath: '/dashboard/parent'
      preLoaderRoute: typeof DashboardParentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/school': {
      id: '/dashboard/school'
      path: '/school'
      fullPath: '/dashboard/school'
      preLoaderRoute: typeof DashboardSchoolRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AlumniRouteChildren {
  AlumniIndexRoute: typeof AlumniIndexRoute
}

const AlumniRouteChildren: AlumniRouteChildren = {
  AlumniIndexRoute: AlumniIndexRoute,
}

const AlumniRouteWithChildren =
  AlumniRoute._addFileChildren(AlumniRouteChildren)

interface DashboardRouteChildren {
  DashboardChildRoute: typeof DashboardChildRoute
  DashboardGroupRoute: typeof DashboardGroupRoute
  DashboardParentRoute: typeof DashboardParentRoute
  DashboardSchoolRoute: typeof DashboardSchoolRoute
  DashboardTeacherRoute: typeof DashboardTeacherRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChildRoute: DashboardChildRoute,
  DashboardGroupRoute: DashboardGroupRoute,
  DashboardParentRoute: DashboardParentRoute,
  DashboardSchoolRoute: DashboardSchoolRoute,
  DashboardTeacherRoute: DashboardTeacherRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumniRoute: AlumniRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
